# -*- coding: utf-8 -*-
"""Task1 sales.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N0fQ_nFrett_uehO85VblYokMg_1kUgc

**Step-1:Libraries Import and Dataset Load **
"""

import pandas as pd

import matplotlib.pyplot as plt

import seaborn as sns

from google.colab import files

uploaded = files.upload()

df = pd.read_csv("sales_data_sample.csv", encoding="latin1")

print(df.shape)

df.head()

"""**Step-2: Data Cleaning:**"""

df['ORDERDATE'] = pd.to_datetime(df['ORDERDATE'], errors='coerce')

print(df.isnull().sum())

df_clean = df.drop(['PHONE','ADDRESSLINE2','POSTALCODE'], axis=1)

df_clean = df_clean.drop_duplicates()

print("After cleaning:", df_clean.shape)

"""** Step 3: Exploratory Data Analysis:**

1. Overall Sales Trend (Year-wise)
"""

sales_year = df_clean.groupby("YEAR_ID")['SALES'].sum().reset_index()

plt.figure(figsize=(6,4))

sns.barplot(x="YEAR_ID", y="SALES", data=sales_year, palette="viridis")

plt.title("Year-wise Sales")

plt.show()

"""2. Monthly Sales Trend"""

monthly_sales = df_clean.groupby("MONTH_ID")['SALES'].sum().reset_index()

plt.figure(figsize=(6,4))

sns.lineplot(x="MONTH_ID", y="SALES", data=monthly_sales, marker="o")

plt.title("Monthly Sales Trend")

plt.show()

"""3. Top 10 Customers by Sales"""

top_customers = df_clean.groupby("CUSTOMERNAME")['SALES'].sum().nlargest(10).reset_index()

plt.figure(figsize=(8,5))

sns.barplot(y="CUSTOMERNAME", x="SALES", data=top_customers, palette="magma")

plt.title("Top 10 Customers by Sales")

plt.show()

"""4. Product Line-wise Sales"""

prod_sales = df_clean.groupby("PRODUCTLINE")['SALES'].sum().reset_index()

plt.figure(figsize=(8,5))

sns.barplot(x="PRODUCTLINE", y="SALES", data=prod_sales, palette="Set2")

plt.xticks(rotation=45)

plt.title("Product Line-wise Sales")

plt.show()

"""5. Deal Size-wise Sales"""

deal_sales = df_clean.groupby("DEALSIZE")['SALES'].sum().reset_index()

plt.figure(figsize=(6,4))

sns.barplot(x="DEALSIZE", y="SALES", data=deal_sales, palette="coolwarm")

plt.title("Sales by Deal Size")

plt.show()